### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Scrxtchy** [MarkCWirt/MIDIUtil#17]
When saving the object as a file, I get this error
```
    mf.writeFile(outf)
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1377, in writeFile
    self.close()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1427, in close
    self.tracks[i].closeTrack()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 523, in closeTrack
    self.removeDuplicates()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 505, in removeDuplicates
    self.eventList.sort(key=sort_events)
TypeError: '<' not supported between instances of 'str' and 'int'
```

This is actually just because I was handling my midi note values as strings, not ints, this actually took me ten minutes to realise (since I'm parsing from XML)
It would be helpful to have some error checking built in to prevent this from happening

**Comment by Wolf-at-SO** [comment]
Would you think it's correct to convert all strings into `int` before the actual sorting?
BTW the line numbers seem to have changed between the version you are using and the recent version, for instance the [`removeDuplicate` function is currently on line 513](https://github.com/MarkCWirt/MIDIUtil/blob/master/src/midiutil/MidiFile.py#L513)

**Comment by Wolf-at-SO** [comment]
... unfortunately converting to `int` (even when called for `int` values) will not be for free:

    > python
    Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import timeit
    >>> timeit.timeit("x=int(v)", setup="v='10000'")
    0.21512968943729235
    >>> timeit.timeit("x=int(v)", setup="v=10000")
    0.12849029212195973
    >>> timeit.timeit("x=v",      setup="v=10000")
    0.02057682789353521

If at all, I'd suggest adding it when events are created. Another option would be some *check* function that can be called for getting informations *if* errors occur.

**Comment by Scrxtchy** [comment]
I wouldn't call myself an expert on the topic, but as much as try_catch to raise awareness of submission of incorrect data into the note 

I am using the latest release from pypi, the git just has unreleased changes
https://github.com/MarkCWirt/MIDIUtil/compare/1.1.3...master

**Comment by Wolf-at-SO** [comment]
You mean to add (at the end of `removeDuplicates`) something like this?:
~~~
try:
    self.eventList.sort(key=sort_events)
TypeError:
    print("mixed types for event.time")
~~~

I'm not sure if the message would be sufficient informative and the check specific enough. As I understand, the [sort_events](https://github.com/MarkCWirt/MIDIUtil/blob/master/src/midiutil/MidiFile.py#L1610) function generates a threefold key, is it safe to assume that `ord` and `insertion_order` will be `int`?

BTW: the function should probably be renamed into `sort_key`, `event_key`, or `event_sort_key` ...

**Comment by Scrxtchy** [comment]
This error is thrown any time `self.eventList.sort(key=sort_events)` is called, if `removeDuplicates` was set to face when creating the MidiFile object, it will just hit a typeError exception the next time a sort is done

**Comment by MarkCWirt** [comment]
> This error is thrown any time `self.eventList.sort(key=sort_events)` is called, if `removeDuplicates` was set to face when creating the MidiFile object, it will just hit a typeError exception the next time a sort is done.

I'm not sure that I understand. I tried to reproduce this by setting `removeDuplicates` to false and then repeatedly sorting the event list with key=sort_events, and I was not able to. If you have a short code example that throws this error it may make it easier to track down the issue.

In terms of the types: I'm all for making things easier to use, but my preference would be to make the documentation a little more explicit. One *could* try to automatically cast the arguments to a number (and wrap in a `try` if that fails), but is doesn't feel particularly "pythonic." But short of that, I'm open to suggestion on error checking that you all may find helpful!

**Comment by Scrxtchy** [comment]
```
mf = MIDIFile(1)
mf.addNote(0,0, '87', '87', '87', '100')
with open('test.middidsfi', 'wb') as outf:
 mf.writeFile(outf)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1377, in writeFile
    self.close()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1433, in close
    origin = self.findOrigin()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1455, in findOrigin
    if track.MIDIEventList[0].time < origin:
TypeError: '<' not supported between instances of 'str' and 'int'
```

```
>>> mf = MIDIFile(1, removeDuplicates=False)
>>> mf.addNote(0,0, '87', '87', '87', '100')
>>> with open('test.middidsfi', 'wb') as outf:
...  mf.writeFile(outf)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1377, in writeFile
    self.close()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1433, in close
    origin = self.findOrigin()
  File "C:\Users\Scratch\AppData\Local\Programs\Python\Python36\lib\site-packages\midiutil\MidiFile.py", line 1455, in findOrigin
    if track.MIDIEventList[0].time < origin:
TypeError: '<' not supported between instances of 'str' and 'int'
>>>
```

**Comment by MarkCWirt** [comment]
OK. I understand now. You're saying that it happens *when* you pass in the strings as parameters, not integers.

As I mentioned above, I don't really want to perform an implicit cast (python duck-typing and all).

The code in the `develop` branch creates the midi stream at the time the note is created, and with this code the error is somewhat more understandable:
```
Traceback (most recent call last):
  File "error.py", line 5, in <module>
    mf.writeFile(outf)
  File "/usr/really-local/MIDIUtil/src/midiutil/MidiFile.py", line 1644, in writeFile
    self.close()
  File "/usr/really-local/MIDIUtil/src/midiutil/MidiFile.py", line 1706, in close
    self.tracks[i].writeMIDIStream()
  File "/usr/really-local/MIDIUtil/src/midiutil/MidiFile.py", line 835, in writeMIDIStream
    self.writeEventsToStream()
  File "/usr/really-local/MIDIUtil/src/midiutil/MidiFile.py", line 852, in writeEventsToStream
    self.MIDIdata += event.serialize(previous_event_tick)
  File "/usr/really-local/MIDIUtil/src/midiutil/MidiFile.py", line 124, in serialize
    midibytes += struct.pack('>B', self.pitch)
struct.error: required argument is not an integer
```
`required argument is not an integer` is probably explicit enough, so I'm going to call this one done.

Thanks for pointing this out! And thank you @Wolf-at-SO for your suggestion. Wrapping the sort in a try was a good suggestion, it just wasn't needed (IMO) with the new develop code.
