### ISSUE TITLE
crash when have simultaneous notes of same pitch

### ISSUE THREAD

**Issue by davidpanderson** [MarkCWirt/MIDIUtil#38]
writeFile() crashes if there are two simultaneous notes of the same pitch.
Example:

    f = MIDIFile(1)
    f.addTempo(0, 0, 120)
    f.addNote(0, 0, 60, 0, .5, 64);
    f.addNote(0, 0, 60, 0, .4, 64);
    with open("test.midi", "wb") as file:
        f.writeFile(file)

produces:

Traceback (most recent call last):
  File "C:\Users\davea\Documents\Personal\Music\music\test.py", line 36, in <module>
    test()
  File "C:\Users\davea\Documents\Personal\Music\music\test.py", line 34, in test
    f.writeFile(file)
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\midiutil\MidiFile.py", line 1637, in writeFile
    self.close()
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\midiutil\MidiFile.py", line 1688, in close
    self.tracks[i].closeTrack()
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\midiutil\MidiFile.py", line 826, in closeTrack
    self.processEventList()
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\midiutil\MidiFile.py", line 789, in processEventList
    self.deInterleaveNotes()
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\midiutil\MidiFile.py", line 889, in deInterleaveNotes
    stack[noteeventkey].pop()
IndexError: pop from empty list

**Comment by davidpanderson** [comment]
Oops,  this is the same as #34 and I see there's a fix.  Can someone please merge it?
